config/routes.rb
Shieldformen::Application.routes.draw do
    
  
  resources :discounts

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  resources :sizes

  get 'confirmation' => 'confirmation#index'

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end

  root :to => 'static_pages#home'

  match '/works',             to: 'static_pages#works'
  match '/tips',              to: 'static_pages#tips'
  match '/tips/benefits',     to: 'static_pages#benefits'
  match '/tips/moisturizers', to: 'static_pages#moisturizers'
  match '/tips/cleansers',    to: 'static_pages#cleansers'
  match '/about',             to: 'static_pages#about'
  match '/about/values',      to: 'static_pages#values'
  match '/about/natural',     to: 'static_pages#natural'
  match '/about/ingredients', to: 'static_pages#ingredients'
  match '/about/team',        to: 'static_pages#team'
  match '/about/jobs',        to: 'static_pages#jobs'
  match '/store',             to: 'store#index'
  match '/privacy',           to: 'static_pages#privacy'
  match '/shipping',          to: 'static_pages#shipping'
  match '/ccv2',              to: 'static_pages#ccv2'

  resources :line_items do
    post 'decrement', on: :member
    post 'increment', on: :member
  end

  resources :discounts do
    post 'apply', on: :member
  end


  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items, dependent: :destroy
  has_many :discounts

  def add_product (product_id)
  	current_item = line_items.find_by_product_id(product_id)
  	if current_item
  		current_item.quantity += 1
  	else
  		current_item = line_items.build(product_id: product_id)
  	end
  	current_item
  end

  def total_price
  	line_items.to_a.sum { |item| item.total_price }
  end

  def discount_price
    total_price = line_items.to_a.sum { |item| item.total_price }
    total_price = total_price - (total_price * 0.30)
  end

  def decrement_line_item_quantity(line_item_id)
    current_item = line_items.find(line_item_id)

    if current_item.quantity > 1
      current_item.quantity -= 1
    else
      current_item.destroy
    end

    current_item
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, only: [:create, :update, :destroy, :show, :new, :index]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
    @cart = current_cart
    respond_to do |format|
      format.html { redirect_to @cart }
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])
    
    #session[:quantity] = @line_item.quantity

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_path, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="sc-wrapper">	

		<table id="cart">
			<% if @cart.line_items.empty? %>
				<p>Your shopping cart is empty.</p>
			<% else %>
			<tr>
				<th align="center">Quantity</th>
				<th align="center">Item</th>
				<th align="center">Unit Price</th>
				<th align="center">Subtotal</th>
				<th align="center">Add/Remove</th>
			</tr>
			
				<%= render (@cart.line_items) %>
			<tr>
				<td colspan="3" class="shipping_label first" align="right"><span style="align: right;"><strong>Shipping &amp; Handling</strong></span></td>
				<td colspan="1" class="shipping_price last" align="right">$0.00</td>
			</tr>
			<% if session[:discount] == 'true' %>
			<tr>
				<td colspan="3" class="shipping_label first" align="right"><span style="align: right;"><strong>Discount Applied</strong></span></td>
				<td colspan="1" class="shipping_price last" align="right">- <%= number_to_currency(@cart.total_price - @cart.discount_price) %></td>
			</tr>
			<% end %>
			<tr>
				<td colspan="3" class="total_label first" align="right"><strong>Total</strong></td>
				<td colspan="1" class="total_price last" align="right">
					<% if session[:discount] == 'true' %>
						<%= number_to_currency(@cart.discount_price) %>
					<% else %>
						<%= number_to_currency(@cart.total_price) %>
					<% end %>
				</td>
			</tr>
			<% end %>
		</table>

</div><!-- end sc-wrapper -->

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div id="content">  
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<div class="shopping-cart">
	<h2>Your Shopping Cart</h2>
	<p>Please use this form to update your shopping cart. You may change the quantities, move items to your wish list for future purchasing, or remove items entirely. The shipping and handling cost is based upon the order total. When you are ready to complete your purchase, please click Checkout to be taken to a secure page for processing.</p>
	<%= render @cart %>

	<div class="update_cart">
		<%= link_to image_tag("empty_cart.png"), cart_path, method: :delete %>
	</div><!-- end update_cart -->
	<div class="checkout">
		<%= link_to image_tag("checkout.png"),  new_order_path, method: :get %>
	</div><!-- end checkout -->

	<div class="clearfix"></div>

</div><!-- end shopping-cart -->	
</div><!-- end content -->

	<div class="clearfix"></div>