config/routes.rb
Shieldformen::Application.routes.draw do
    
  
  resources :discounts

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  resources :sizes

  get 'confirmation' => 'confirmation#index'

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end

  root :to => 'static_pages#home'

  match '/works',             to: 'static_pages#works'
  match '/tips',              to: 'static_pages#tips'
  match '/tips/benefits',     to: 'static_pages#benefits'
  match '/tips/moisturizers', to: 'static_pages#moisturizers'
  match '/tips/cleansers',    to: 'static_pages#cleansers'
  match '/about',             to: 'static_pages#about'
  match '/about/values',      to: 'static_pages#values'
  match '/about/natural',     to: 'static_pages#natural'
  match '/about/ingredients', to: 'static_pages#ingredients'
  match '/about/team',        to: 'static_pages#team'
  match '/about/jobs',        to: 'static_pages#jobs'
  match '/store',             to: 'store#index'
  match '/privacy',           to: 'static_pages#privacy'
  match '/shipping',          to: 'static_pages#shipping'
  match '/ccv2',              to: 'static_pages#ccv2'

  resources :line_items do
    post 'decrement', on: :member
    post 'increment', on: :member
  end

  resources :discounts do
    post 'apply', on: :member
  end


  
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :image_url, :name, :price, :size_id, :stock

  has_many :line_items
  has_many :orders, through: :line_items
  has_many :sizes

  validates :name, :description, :image_url, :stock, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :name, uniqueness: true
  validates :image_url, allow_blank: true, format: { 
  	with: 		%r{\.(gif|jpg|png)$}i,
  	message: 'must be a URL for GIF, JPG or PNG image.'
  }

  before_destroy :ensure_not_referenced_by_any_line_item

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
  	if line_items.empty?
  		return true
  	else
  		errors.add(:base, 'Line Items present')
  		return false
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :authorize, only: :show
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @cart = current_cart
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @cart = current_cart
    @sizes = @product.sizes.paginate(page: params[:page])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @cart = current_cart
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @cart = current_cart
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    @cart = current_cart
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
      format.atom
    end
  end

  
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 50, 
              :class => 'formInputText' %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => 50, 
              :class => 'formInputTextArea' %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url, :size => 50, 
              :class => 'formInputText' %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price, :size => 50, 
              :class => 'formInputText' %>
  </div>
  <div class="field">
    <%= f.label :stock %><br />
    <%= f.number_field :stock, :size => 50, 
              :class => 'formInputText' %>
  </div>
  <div class="field">
    <%= f.label :size_id %><br />
    <%= f.number_field :size_id, :size => 50, 
              :class => 'formInputText' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div id="content">
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div><!-- end content -->

app/views/products/index.html.erb
<div id="content">
<h1>Listing products</h1>

<table>
<% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td>
      <%= image_tag(product.image_url, class: 'list_image') %>
    </td>

    <td class="list-description">
      <dl>
        <dt><strong>Name:</strong> <%= product.name %></dt>
        <dt><strong>Description:</strong> <%= strip_tags(product.description) %></dt> 
        <dt><strong>Price:</strong> <%= number_to_currency(product.price) %></dt>
        <dt><strong>Stock: </strong><%= product.stock %></dt>

      </dl>
    </td>
    <td class="list_action">
      <%= link_to 'Show', product %><br/>
      <%= link_to 'Edit', edit_product_path(product) %><br/>
      <%= link_to 'Destroy', product,
                  confirm: 'Are you sure?',
                  method: :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>
</div><!-- end content -->

app/views/products/new.html.erb
<div id="content">
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>
</div><!-- end content -->

app/views/products/show.html.erb
<div id="content">  
  <% if notice %>
    <p class="notification notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="notification alert">
      <%= alert %>
    </p>
  <% end %>
  <div class="product-image">
    <img src="<%= image_path @product.image_url %>" alt="" border="0" />
  </div><!-- end product-image -->
  
  <div class="product-info">
    <h2><%= @product.name %></h2>
    
    <p>Price: <span class="price"><%= number_to_currency(@product.price) %></span></p>
    
    <% @product.sizes.each do |size| %>
    <p>Sizes:</p>
    <select class="productSelect" name="sizes">
      <option value="<%= size.size %>"><%= size.size %></option>
    </select>
    <% end %>
    
    <p>Fragrance:</p>
    <select class="productSelect" name="fragrance">
      <option value="fragrance free">Fragrance Free</option>
    </select>
    
    <div class="add_to_cart">
      <%= link_to image_tag("add_to_cart.png"),  line_items_path(product_id: @product.id), method: :post %>
    </div>
    
  </div><!-- end product-info -->

  <div class="clearfix"></div>
  <hr />
  
    <div class="image-thumbnails">
      <a href="#"><img src="<%= image_path "thumbnail.png" %>" alt="thumbnail" width="59" height="60" border="0" /></a>
      <a href="#"><img src="<%= image_path "thumbnail.png" %>" alt="thumbnail" width="59" height="60" border="0" /></a>
      <a href="#"><img src="<%= image_path "thumbnail.png" %>" alt="thumbnail" width="59" height="60" border="0" /></a>
    </div><!-- end image-thumbnails -->
  
    <div class="box">

      <ul class="css-tabs">
        <li><a href="#content_1" title="content_1" class="tab active">Description</a></li>
        <li><a href="#content_2" title="content_2" class="tab">Key Ingredients</a></li>
      </ul>

    
    <div class="css-panes">
      <div id="content_1" class="content">
        <%= strip_tags(@product.description) %>
      </div><!-- end description -->
    
      
      <div id="content_2" class="content">
        <p><ul><li><strong>Vitamin E</strong> - anti-inflammatory, antioxidant, emollient</li><li><strong>Pro-vitamin B</strong> – soothing, calming</li><li><strong>Tea Tree Oil</strong> – medicinal: acne, burns, rashes, skin immune deficiencies, and sebum regulation for oily skin</li><li><strong>Green Tea Extract</strong> – antioxidant, soothing anti-inflammatory</li><li><strong>Ylang Ylang E.O.</strong> – antibacterial, antiseptic, anti-sebum</li><li><strong>Patchouli E.O.</strong> – anti bacterial, anti-inflammatory, antiseptic, antistringent, cell-regenerating</li><li><strong>Rosewood E.O.</strong> – cell regenerator, antiseptic</li><li><strong>Cedarwood E.O.</strong> – regenerative, cleansing</li></ul></p>
      </div><!-- end ingredients -->
    </div><!-- end content -->
      
      
    </div><!-- end box -->
  
  <div class="clearfix"></div>
<script type="text/javascript" src="https://s3.amazonaws.com/static.appsumo.com/2a53a3e5fd6cd4652e9a13a51fbf54b899978bd4/js/jquery.tools.min.js"></script>

<!-- activate tabs with JavaScript -->
<script>
  $(function() {
  // :first selector is optional if you have only one tabs on the page
  $(".css-tabs:first").tabs(".css-panes:first > div");
  });
</script>

  
</div><!-- end content -->
<div class="clearfix"></div>