config/routes.rb
Shieldformen::Application.routes.draw do
    
  
  resources :discounts

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  resources :sizes

  get 'confirmation' => 'confirmation#index'

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end

  root :to => 'static_pages#home'

  match '/works',             to: 'static_pages#works'
  match '/tips',              to: 'static_pages#tips'
  match '/tips/benefits',     to: 'static_pages#benefits'
  match '/tips/moisturizers', to: 'static_pages#moisturizers'
  match '/tips/cleansers',    to: 'static_pages#cleansers'
  match '/about',             to: 'static_pages#about'
  match '/about/values',      to: 'static_pages#values'
  match '/about/natural',     to: 'static_pages#natural'
  match '/about/ingredients', to: 'static_pages#ingredients'
  match '/about/team',        to: 'static_pages#team'
  match '/about/jobs',        to: 'static_pages#jobs'
  match '/store',             to: 'store#index'
  match '/privacy',           to: 'static_pages#privacy'
  match '/shipping',          to: 'static_pages#shipping'
  match '/ccv2',              to: 'static_pages#ccv2'

  resources :line_items do
    post 'decrement', on: :member
    post 'increment', on: :member
  end

  resources :discounts do
    post 'apply', on: :member
  end


  
end

app/views/layouts/_action.html.erb
<div id="action">
	<div id="products" class="container">
		<h2><a href="/store">Our Products</a></h2>
		<a href="/store"><span class="products-image"></span></a>
		<p>Check out our range of masculine products to keep your looking your best.</p>
	</div><!-- end products -->
	<div id="grooming" class="container">
		<h2><a href="/tips">Grooming Tips</a></h2>
		<a href="/tips"><span class="grooming-image"></span></a>
		<p>Come discover, learn, and explore topics surrounding modern masculinity.</p>
	</div><!-- end grooming -->
	<div id="videos" class="container">
		<h2><a href="/tips">Watch Our Videos</a></h2>
		<a href="/tips"><span class="videos-image"></span></a>
		<p>Check out our latest grooming tips that'll keep your feeling your most confident at all times.</p>
	</div><!-- end videos -->
	<div id="organic" class="container">
		<h2><a href="/about/natural">100% Organic</a></h2>
		<a href="/about/natural"><span class="organic-image"></span></a>
		<p>Rest assured knowing that our products are made from natural 100% organic ingredients.</p>
	</div><!-- end organic -->
</div><!-- end action -->

app/views/layouts/_footer.html.erb
<footer>
<div id="footer-inner">
	
	<div class="left">
		<p>© 2012 Shield For Men. All Rights Reserved</p>
		<ul>
			<li><a href="/privacy">Privacy Policy</a></li> |
			<li><a href="/shipping">Shipping &amp; Return Policy</a></li>
		</ul>
	</div><!-- left -->
	
	<div class="right">
		<div class="social-media-icons">
			<ul>
				<li><a href="http://www.facebook.com/shieldformen" target="_blank"><span class="facebook"></span></a></li>
				<li><a href="https://twitter.com/#!/shieldformen/" target="_blank"><span class="twitter"></span></a></li>
				<li><a href="http://www.flickr.com/photos/shieldformen/" target="_blank"><span class="flickr"></span></a></li>
				<li><a href="http://www.youtube.com/shieldformenvideos/" target="_blank"><span class="youtube"></span></a></li>
			</ul>
		</div><!-- social-media-icons -->
	</div><!-- right -->
</div><!-- footer-inner -->
</footer>

app/views/layouts/_header.html.erb
<div id="header">
			<%= link_to "shieldformen", root_path, id: "logo" %>

			<div class="clearfix"></div>
			<nav>
				<ul class="menu lgray" id="menu">

					<li><%= link_to "Home", 			root_path %></li>

					<li><%= link_to "Products", 	store_path %>
						<!-- start mega menu -->
						<div class="cols3">
							<div class="col3">
								<h4>Choose one of our products below.</h4>
							</div>
							<div class="col1">
								<h5>Packages</h5>
								<ol>
								    <li><a href="/products/5">Full Package</a></li>
								</ol>
							</div>
							<div class="col1">
								<h5>Cleanser</h5>
								<ol>
								    <li><a href="/products/4">Wash + Protect</a></li>
								</ol>
							</div>
							<div class="col1">
								<h5>Moisturizer</h5>
								<ol>
								    <li><a href="products/3">Moisturize + Shield</a></li>
								</ol>
							</div>

							<div class="col1">
								<h5>All Natural</h5>
								<p>Our products are made with all natural, organic ingredients and specifically formulated for men.</p>
							</div>
						</div>
						<!-- end mega menu -->
					</li>

					<li><%= link_to "How It Works", 	works_path %></li>

					<li><%= link_to "Grooming Tips",  tips_path %></li>

					<li><%= link_to "Our Blog", 			'http://blog.shieldformen.com', 
										:target => "_blank" %></li>

					<li><%= link_to "About Us", 			about_path %></li>

					<% if session[:user_id] %>
					<li class="floatr"><%= link_to "Admin", admin_path %>
						<div class="cols4">
							<div class="col1">
								<h5>Orders</h5>
								<ol>
									<li><%= link_to 'List Orders', orders_path %></li>
								</ol>
							</div>
							<div class="col1">
								<h5>Products</h5>
								<ol>
									<li><%= link_to 'List Products', products_path %></li>
									<li><%= link_to 'Add Product', new_product_path %></li>
								</ol>
							</div>
							<div class="col1">
								<h5>Sizes</h5>
								<ol>
									<li><%= link_to 'List Sizes', sizes_path %></li>
									<li><%= link_to 'Add Size', new_size_path %></li>
								</ol>
							</div>
							<div class="col1">
								<h5>Users</h5>
								<ol>
									<li><%= link_to 'List Users', users_path %></li>
									<li><%= link_to 'Add User', new_user_path %></li>
								</ol>
							</div>
							<div class="col1">
								<h5>Discounts</h5>
								<ol>
									<li><%= link_to 'List Discount Codes', discounts_path %></li>
									<li><%= link_to 'Add Discount Code', new_discount_path %></li>
								</ol>
							</div>
							<div class="col1">
								<h5>Logout</h5>
								<ol>
									<li><%= link_to 'Logout', logout_path, method: :delete %></li>
								</ol>
							</div>
						</div>
					</li>
					<% end %>

					<li class="floatr"><%= link_to "View Cart", carts_path %>
						<!-- start mega menu -->
						<div class="cols3" id="styles">
							<div class="col3"><h4>Your Shopping Cart</h4></div>

								<%= render('orders/shoppingcart') %>

						</div>
						<!-- end mega menu -->
					</li>
				</ul>
			</nav>
			
			
			
			
		</div><!-- end header -->
		<div class="clearfix"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
<div id="wrapper">
	<div id="container">
		<%= render 'layouts/header' %>

		<%= yield %>
		
		<%= render 'layouts/action' %>
		
    <%= render 'layouts/footer' %>
		
  </div><!-- end container -->
</div><!-- end wrapper -->
</body>
</html>